# Generated by Django 4.0.4 on 2022-05-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='type',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='choice',
            name='decisions',
        ),
        migrations.AddField(
            model_name='choice',
            name='decisions',
            field=models.ManyToManyField(to='choices.decision'),
        ),
    ]
