# Generated by Django 4.0.4 on 2022-05-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0003_rename_type_effect_effect_type_and_more'),
        ('data', '0002_rename_num_effect_car_effects_player_effects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='effects',
        ),
        migrations.AddField(
            model_name='car',
            name='effects',
            field=models.ManyToManyField(to='choices.effect'),
        ),
        migrations.RemoveField(
            model_name='house',
            name='num_effect',
        ),
        migrations.AddField(
            model_name='house',
            name='num_effect',
            field=models.ManyToManyField(to='choices.effect'),
        ),
        migrations.RemoveField(
            model_name='player',
            name='house',
        ),
        migrations.AddField(
            model_name='player',
            name='house',
            field=models.ManyToManyField(to='data.house'),
        ),
    ]
