# Generated by Django 4.0.4 on 2022-05-20 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_car_effects_car_effects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='house',
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='data.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='data.player'),
            preserve_default=False,
        ),
    ]
