# Generated by Django 4.0.4 on 2022-05-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='credit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='interest',
            field=models.IntegerField(),
        ),
    ]
