# Generated by Django 4.0.4 on 2022-05-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_player_credit_alter_player_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='interest',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
