# Generated by Django 4.0.4 on 2022-05-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_car_description_alter_car_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(),
        ),
    ]
