# Generated by Django 4.0.4 on 2022-05-20 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_car_description_alter_house_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='description',
            new_name='car_description',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='name',
            new_name='car_name',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='description',
            new_name='house_description',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='name',
            new_name='house_name',
        ),
    ]
